### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by DarthBinks93** [nithinphilips/spotifyscrape#1] opened 2015-11-05 20:56 UTC
This is the full output when I try to run this program: 
Traceback (most recent call last):
  File "/home/steven/spotifyscrape/venv/bin/spotifyscrape", line 9, in <module>
    load_entry_point('spotifyscrape==0.2.0', 'console_scripts', 'spotifyscrape')()
  File "/home/steven/spotifyscrape/venv/local/lib/python2.7/site-packages/spotifyscrape-0.2.0-py2.7.egg/spotifyscrape/spotifyscrape.py", line 44, in main
    parser.dispatch()
  File "build/bdist.linux-x86_64/egg/argh/helpers.py", line 55, in dispatch
  File "build/bdist.linux-x86_64/egg/argh/dispatching.py", line 174, in dispatch
  File "build/bdist.linux-x86_64/egg/argh/dispatching.py", line 277, in _execute_command
  File "build/bdist.linux-x86_64/egg/argh/dispatching.py", line 265, in _call
  File "/home/steven/spotifyscrape/venv/local/lib/python2.7/site-packages/spotifyscrape-0.2.0-py2.7.egg/spotifyscrape/allaccessimport.py", line 54, in allaccessimport
    logged_in = api.login(username, password)
TypeError: login() takes exactly 4 arguments (3 given)
Searching for aesop96's playlist 1fZ8uFmdK7L1q8h6ybiK0K
Traceback (most recent call last):
  File "/home/steven/spotifyscrape/venv/bin/spotifyscrape", line 9, in <module>
    load_entry_point('spotifyscrape==0.2.0', 'console_scripts', 'spotifyscrape')()
  File "/home/steven/spotifyscrape/venv/local/lib/python2.7/site-packages/spotifyscrape-0.2.0-py2.7.egg/spotifyscrape/spotifyscrape.py", line 44, in main
    parser.dispatch()
  File "build/bdist.linux-x86_64/egg/argh/helpers.py", line 55, in dispatch
  File "build/bdist.linux-x86_64/egg/argh/dispatching.py", line 174, in dispatch
  File "build/bdist.linux-x86_64/egg/argh/dispatching.py", line 277, in _execute_command
  File "build/bdist.linux-x86_64/egg/argh/dispatching.py", line 260, in _call
  File "/home/steven/spotifyscrape/venv/local/lib/python2.7/site-packages/spotifyscrape-0.2.0-py2.7.egg/spotifyscrape/spotifyexport.py", line 168, in exportplaylist
    csv_write_tracks(writer, tracks)
  File "/home/steven/spotifyscrape/venv/local/lib/python2.7/site-packages/spotifyscrape-0.2.0-py2.7.egg/spotifyscrape/spotifyexport.py", line 181, in csv_write_tracks
    csv_write_track(writer, track)
  File "/home/steven/spotifyscrape/venv/local/lib/python2.7/site-packages/spotifyscrape-0.2.0-py2.7.egg/spotifyscrape/spotifyexport.py", line 189, in csv_write_track
    writer.writerow([title, artist, album])
IOError: [Errno 32] Broken pipe

**Comment by nithinphilips** [comment] 2015-11-13 15:33
Can you share some additional details so I can try to replicate the issue?

What is your Linux Distribution? 32 or 64-bit?

What is the command and arguments that caused the issue?

Just based on the logs it looks like you were exporting from Spotify and importing it into Google Play via something like `..export-playlist... | spotifyscrape import`. It's possible that root cause is that the import command failed and broke the pipe. Verify your All Access credentials in `.spotifyscrape`. Keep in mind that if you use two-factor authentication, you need to create an application password for SpotifyScrape. Entering your Google password won't work.

**Comment by DarthBinks93** [comment] 2015-11-13 19:29
Thanks for the reply, but I actually don't need help with this anymore. I
managed to get pyportify working and used that instead.

**Comment by nithinphilips** [comment] 2015-11-16 19:45
Thanks for the update. I will go ahead and close the issue.

**Closed as completed by nithinphilips** 2015-11-16 19:45 UTC
